name: 개선사항
description: 기능 개선을 위한 제안서
title: '[개선] '
labels: improvements
body:
  - type: textarea
    id: description
    attributes:
      label: 개선 사항
      description: 문제가 무엇인지 또는 개선하고자 하는 기능이 무엇인지에 대한 명확하고 간결한 설명입니다.
      placeholder: 이런게 아쉬워요...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 대체 솔루션 또는 기능
      description: (optional) 고려한 대체 솔루션이나 기능에 대해 명확하고 간결하게 설명합니다.
  - type: textarea
    id: additional-context
    attributes:
      label: 레퍼런스
      description: (optional) 해당 개선에 대한 레퍼런스를 제공해 주세요.
